"""Backward-compatible shims for relocated persistence models."""
from __future__ import annotations

from warnings import warn

warn(
    "exegesis.infrastructure.api.app.db.models is deprecated; import from "
    "exegesis.adapters.persistence.models instead",
    DeprecationWarning,
    stacklevel=2,
)

# Explicitly re-export the upstream persistence models so each dependency is obvious.
from exegesis.infrastructure.api.app.persistence_models import (
    AgentStep,
    AgentTrail,
    AnalyticsTopicMapEdge,
    AnalyticsTopicMapNode,
    AnalyticsTopicMapSnapshot,
    Any,
    AppSetting,
    AuditLog,
    Base,
    Boolean,
    ChatSession,
    CollectionItem,
    CollectionItemType,
    CommentaryExcerptSeed,
    ContradictionSeed,
    CorpusSnapshot,
    Creator,
    CreatorClaim,
    CreatorVerseRollup,
    CrossReference,
    Date,
    DateTime,
    DeclarativeBase,
    Discovery,
    Document,
    DocumentAnnotation,
    EntryMention,
    Enum,
    EvidenceCard,
    FeedbackEvent,
    FeedbackEventAction,
    Float,
    ForeignKey,
    GeoAncientPlace,
    GeoGeometry,
    GeoImage,
    GeoModernLocation,
    GeoPlace,
    GeoPlaceVerse,
    HarmonySeed,
    Hypothesis,
    Index,
    IngestionJob,
    IntArrayType,
    Integer,
    JSON,
    Mapped,
    NoteEvidence,
    Notebook,
    NotebookCollaborator,
    NotebookCollaboratorRole,
    NotebookEntry,
    Passage,
    PassageEmbedding,
    PassageVerse,
    ResearchCollection,
    ResearchNote,
    SQLEnum,
    String,
    TSVectorType,
    TYPE_CHECKING,
    Text,
    TopicMapEdgeType,
    TopicMapNodeType,
    TrailRetrievalSnapshot,
    TrailSource,
    TranscriptQuote,
    TranscriptQuoteVerse,
    TranscriptSegment,
    TranscriptSegmentVerse,
    UTC,
    UniqueConstraint,
    UserWatchlist,
    VectorType,
    Video,
    WatchlistEvent,
    annotations,
    datetime,
    get_settings,
    hybrid_property,
    isclass,
    mapped_column,
    postgresql,
    relationship,
    select,
    text,
    uuid4,
)
from exegesis.infrastructure.api.app.persistence_models import __all__ as _PERSISTENCE_ALL  # type: ignore

from .dossier import EvidenceDossier  # noqa: F401

__all__ = _PERSISTENCE_ALL + ["EvidenceDossier"]
