"""Backward-compatible shims for relocated persistence models."""
from __future__ import annotations

from warnings import warn

warn(
    "exegesis.infrastructure.api.app.db.models is deprecated; import from "
    "exegesis.adapters.persistence.models instead",
    DeprecationWarning,
    stacklevel=2,
)

# Explicit re-exports from persistence models
from exegesis.infrastructure.api.app.persistence_models import (
    AgentStep,
    AgentTrail,
    AnalyticsTopicMapEdge,
    AnalyticsTopicMapNode,
    AnalyticsTopicMapSnapshot,
    AppSetting,
    AuditLog,
    Base,
    ChatSession,
    CollectionItem,
    CollectionItemType,
    CommentaryExcerptSeed,
    ContradictionSeed,
    CorpusSnapshot,
    Creator,
    CreatorClaim,
    CreatorVerseRollup,
    CrossReference,
    Discovery,
    Document,
    DocumentAnnotation,
    EntryMention,
    EvidenceCard,
    FeedbackEvent,
    FeedbackEventAction,
    GeoAncientPlace,
    GeoGeometry,
    GeoImage,
    GeoModernLocation,
    GeoPlace,
    GeoPlaceVerse,
    HarmonySeed,
    Hypothesis,
    IngestionJob,
    Notebook,
    NotebookCollaborator,
    NotebookCollaboratorRole,
    NotebookEntry,
    NoteEvidence,
    Passage,
    PassageEmbedding,
    PassageVerse,
    ResearchCollection,
    ResearchNote,
    TopicMapEdgeType,
    TopicMapNodeType,
    TrailRetrievalSnapshot,
    TrailSource,
    TranscriptQuote,
    TranscriptQuoteVerse,
    TranscriptSegment,
    TranscriptSegmentVerse,
    UserWatchlist,
    Video,
    WatchlistEvent,
)

from .dossier import EvidenceDossier  # noqa: F401

__all__ = [
    # Persistence models
    "AgentStep",
    "AgentTrail",
    "AnalyticsTopicMapEdge",
    "AnalyticsTopicMapNode",
    "AnalyticsTopicMapSnapshot",
    "AppSetting",
    "AuditLog",
    "Base",
    "ChatSession",
    "CollectionItem",
    "CollectionItemType",
    "CommentaryExcerptSeed",
    "ContradictionSeed",
    "CorpusSnapshot",
    "Creator",
    "CreatorClaim",
    "CreatorVerseRollup",
    "CrossReference",
    "Discovery",
    "Document",
    "DocumentAnnotation",
    "EntryMention",
    "EvidenceCard",
    "FeedbackEvent",
    "FeedbackEventAction",
    "GeoAncientPlace",
    "GeoGeometry",
    "GeoImage",
    "GeoModernLocation",
    "GeoPlace",
    "GeoPlaceVerse",
    "HarmonySeed",
    "Hypothesis",
    "IngestionJob",
    "Notebook",
    "NotebookCollaborator",
    "NotebookCollaboratorRole",
    "NotebookEntry",
    "NoteEvidence",
    "Passage",
    "PassageEmbedding",
    "PassageVerse",
    "ResearchCollection",
    "ResearchNote",
    "TopicMapEdgeType",
    "TopicMapNodeType",
    "TrailRetrievalSnapshot",
    "TrailSource",
    "TranscriptQuote",
    "TranscriptQuoteVerse",
    "TranscriptSegment",
    "TranscriptSegmentVerse",
    "UserWatchlist",
    "Video",
    "WatchlistEvent",
    # Local models
    "EvidenceDossier",
]
